# Generated by Django 5.2 on 2025-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_is_published_alter_post_img_url_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img_url",
            field=models.ImageField(
                max_length=500, null=True, upload_to="posts/images"
            ),
        ),
    ]
