# Generated by Django 5.2.2 on 2025-08-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
