# Generated by Django 5.2.2 on 2026-01-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url_online',
            field=models.URLField(blank=True, help_text='Online image URL (if provided instead of file upload)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/images'),
        ),
    ]
