"""
Django settings for MyApp project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-g3j%()wrxl(3+et^g*6n!5zp@*4ogyrxc+ux&$t3s#f4uu_b(m"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS for Render deployment
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "myblog-c1lu.onrender.com",  # Your specific Render domain
    "*.onrender.com",  # Render free tier domain pattern
    "*",  # Allow all for initial deploy
]

# CSRF Trusted Origins - Required for ngrok and public access
CSRF_TRUSTED_ORIGINS = [
    "https://e0e9e5686e91.ngrok-free.app",  # Your current ngrok URL
    "https://*.ngrok-free.app",  # Allow all ngrok free domains
    "https://*.ngrok.io",  # Allow all ngrok domains
    "http://localhost:8002",
    "http://127.0.0.1:8002",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Must be after SecurityMiddleware, before other middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "MyApp.middleware.RedirectAuthenticatedUserMiddleware",
    "MyApp.middleware.RestrictUnauthenticatedUserMiddleware",
]

ROOT_URLCONF = "MyApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MyApp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite for Render free tier (no shell access for migrations)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# MySQL configuration (for local development - uncomment if needed)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "blog",
#         "USER": "root",
#         "PASSWORD": "Mysql@2002",
#         "HOST": "localhost",
#         "PORT": "3306",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL and STATIC_ROOT are defined at the bottom of this file
# STATICFILES_DIRS - where Django looks for static files during development
STATICFILES_DIRS = [
    BASE_DIR / "blog" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "suryapaulpandi2002@gmail.com"
EMAIL_HOST_PASSWORD = "folv pljw fwvj veif"
# DEFAULT_FROM_EMAIL = "suryapaulpandi2002@gmail.com"
DEFAULT_FROM_EMAIL = "info@surya.com"

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "sandbox.smtp.mailtrap.io"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "21cf5fcb1d21bd"
# EMAIL_HOST_PASSWORD = "fa17ab90ca1eaf"
# DEFAULT_FROM_EMAIL = "info@surya.com"

LOGIN_REDIRECT_URL = "/home/"  # or your named URL pattern
LOGOUT_REDIRECT_URL = "/login/"  # optional

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
LOGIN_URL = "/login"

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 900  # in seconds (15 minutes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # session ends when browser is closed
SESSION_SAVE_EVERY_REQUEST = True  # reset session timer on each request


# OTP Configuration
OTP_EXPIRY_MINUTES = 3  # 10 minute expiration
OTP_EXPIRY_SECONDS = OTP_EXPIRY_MINUTES * 60

# Add to the bottom of settings.py
OTP_EXPIRY_SECONDS = 180  # 3 minutes in seconds
OTP_RESEND_LIMIT = 3  # Max resend attempts

SESSION_SERIALIZER = "blog.custom_json.CustomJSONSerializer"

# Static files configuration for production (Render)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True  # Use Django's finders during development
WHITENOISE_AUTOREFRESH = True  # Auto-refresh static files during development
